language: node_js

node_js:
  - "8"

script:
  - npm run build

cache: npm

branches:
  only:
  - master

deploy:
  provider: heroku
  api_key:
    secure: <your-api-key>
  app: livetravelsampleapp
  on:
    repo: nicholasfay/LiveTravelSampleApp
